- src/scripts/Lists/PlayerList.js
- src/scripts/Lists/TeamList.js
#check out the functions I wrote to render html input forms
> created render functions for new team and new player submit forms

- src/index.html
- src/scripts/TruncheonsFlagons.js
- src/scripts/main.js
Added HTML rendering of current code for Truncheons and Flagons.
> Added html implementation of Truncheons and Flagons page.

- src/scripts/Lists/PlayerList.js
#updated dropdown list to be responsive to API
> teams list dropdown somewhat responsive to API

- src/scripts/Lists/TeamList.js
- src/scripts/TruncheonsFlagons.js
fixed css issue when page reloads after clicking on start game button
> updated start button event listener html

- src/scripts/Lists/TeamList.js
- src/scripts/Providers/TeamProvider.js
- src/scripts/main.js
#check out the API dispatch event I added to teamprovider.js as well as the new event listener for "CustomEvent" in main to re-render the DOM
> added event listener, dispatch for new team submission

- api/database.json
- src/scripts/Lists/TeamList.js
- src/scripts/TruncheonsFlagons.js
- src/scripts/databaseAccess.js
added code for selecting teams after starting gameplay
added some more css styling
steps to test
1. pull code and serve to web browser
2. after clicking on the start button, three dropdowns should appear with the list of teams
3. after selecting a team from each dropdown, round 1 score entry should appear
4. the order in which you select the teams from the dropdowns should not matter, it should always be the third selection that starts the next module
> added code for selecting teams after starting game

- api/database.json
- src/scripts/Lists/ScoreList.js
- src/scripts/TruncheonsFlagons.js
Focused on rendering leaderboard to dom with team names, running number of players, and total running score. Fixed the firstName issue on the database.json file
##Steps to test
1. git fetch --all
2. git checkout anm-leaderboard-html
3. serve and make sure leaderboard team name, player and score render
> Rendering Leaderboard to DOM

- api/database.json
Fixed the JSON file by adding opening "{" at top
> json is now happy

- src/styles/main.css
- src/styles/playerinput.css
- src/styles/teaminput.css
#clone my branch (alex-branch)
#check out and tinker with the styling
#lmk!
> improved styling, i hope

- src/scripts/Lists/TeamList.js
- src/scripts/Providers/ScoreProvider.js
- src/scripts/TruncheonsFlagons.js
- src/scripts/databaseAccess.js
Refactored even listener code to only change game__play section html
> Mec truncheonsx

- src/styles/main.css
- src/styles/playerinput.css
- src/styles/teaminput.css
#pull from this branch
#check how the styling on the display looks
#send me any suggestions for improvement!
> new styling

- api/database.json
- src/scripts/Lists/TeamList.js
- src/scripts/Providers/PlayerProvider.js
- src/scripts/Providers/ScoreProvider.js
- src/scripts/databaseAccess.js
added code to listen for end of round 3, send scores to api, reset temporary state, and re-render html
steps to test
1. pull this branch and serve to web browser
2. after submitting scores to round 3, leaderboard should update with scores from previous game
3. all html should re-render
> Mec truncheons7

- api/database.json
- src/scripts/Providers/ScoreProvider.js
Steps to Test
1. Clone this branch and serve
2. Start a game and enter in the score fields either a number or string.
3. Verify an alert box shows up when a string is entered.
4. Leave a score box empty and submit score.
5. Verify an alert box shows up when a box is left empty.
> added logic that checks the scores entered to ensure they are valid.

- api/database.json
- src/scripts/Lists/TeamList.js
- src/scripts/Providers/TeamProvider.js
#pull to local feature branch
#test out the prevention of multiple of the same team selected in dropdown (not perfectly perfect, i fear)
#suggest logic improvements, if you have any
> Added checks for team names in Team Input module and in Team Dropdown

- api/database.json
- src/styles/currentgame.css
- src/styles/main.css
Steps to Test
1.pull this branch
2. Play a game and verify the size of the round counter is 36px and the names/scores of the teams are 24px.
3. Enjoy!
> Minor style changes on Round counter and current game font size.

- api/database.json
- src/scripts/Providers/PlayerProvider.js
- src/styles/playerinput.css
- src/styles/teaminput.css
Added flex styling to player and team input boxes
> Al featurebranch winnerwinner

- src/styles/main.css
Fixed the small browser responsiveness issue.
##To Test
1. git fetch --all
2. serve this branch 
3. verify a smaller browser size pushes leaderboard below game play
> Responsive styling added

- api/database.json
- src/scripts/Lists/TeamList.js
- src/scripts/Providers/PlayerProvider.js
> implemented new dropdown list function to filter for populated teams

- api/database.json
- src/scripts/TruncheonsFlagons.js
- src/styles/main.css
- src/styles/rules.css
Steps to Test
1. Clone and serve
2. Verify rules section displays correctly 
3. Thanks!
> Added rules section on main page.

- src/scripts/TruncheonsFlagons.js
- src/styles/rules.css
1) pull down this feature branch and check out how the rules box is now rendering
2) send me any suggestions for improvement!
> #edited the rules text and rules box

- api/database.json
- src/scripts/Providers/ScoreProvider.js
Steps to Test
1.Clone to local
2. Play a game and once you hit submit scores on round 3, watch closely to ensure round 4 is NOT displayed before the game resets.
3. Thanks!
> added ternary operator to not display round 4 html when game is over.
